DROP TABLE LOYALTIES;
CREATE TABLE LOYALTIES (
ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CODE varchar(3) NOT NULL,
DESCRIPTION varchar(48),
PRIMARY KEY(ID)
);
DROP TABLE ROUTES;
CREATE TABLE ROUTES (
ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
WORLD_A int NOT NULL,
WORLD_B int NOT NULL,
IMPERIAL boolean NOT NULL,
X_BOAT boolean NOT NULL,
PRIMARY KEY(ID)
);
DROP TABLE SPECIAL_INSTALLATIONS;
CREATE TABLE SPECIAL_INSTALLATIONS (
ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TYPE varchar(32) NOT NULL,
DESCRIPTION varchar(2048) NOT NULL,
PRIMARY KEY(ID)
);
DROP TABLE SECTORS;
CREATE TABLE SECTORS (
ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NAME varchar(32) NOT NULL,
BACKGROUND varchar(2048),
PRIMARY KEY(ID)
);
DROP TABLE SUB_SECTORS;
CREATE TABLE SUB_SECTORS (
ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
SECTOR int NOT NULL,
NAME varchar(32) NOT NULL,
N_NEIGHBOUR int,
E_NEIGHBOUR int,
S_NEIGHBOUR int,
W_NEIGHBOUR int,
BACKGROUND varchar(2048),
PRIMARY KEY(ID)
);
DROP TABLE WORLDS;
CREATE TABLE WORLDS (
ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
SUB_SECTOR int NOT NULL,
NAME varchar(32) NOT NULL,
LOCATION varchar(4) NOT NULL,
STARPORT int NOT NULL,
SIZE int NOT NULL,
ATMOSPHERE int NOT NULL,
HYDROGRAPHICS int NOT NULL,
POPULATION int NOT NULL,
GOVERNMENT int NOT NULL,
LAW_LEVEL int NOT NULL,
TECHNOLOGY int NOT NULL,
BASES varchar(1),
TRADE varchar(48),
NOTES varchar(128),
TAS_TZC varchar(1),
GAS_GIANT boolean NOT NULL,
LOYALTY int NOT NULL,
SPECIAL_INSTALLATIONS int,
SEED int,
PRIMARY KEY(ID)
);