DROP TABLE ADVENTURES;
CREATE TABLE ADVENTURES (
ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
CAMPAIGN_ID INT REFERENCES CAMPAIGNS(ID),
TITLE varchar(128) NOT NULL,
INSTANT varchar(26) NOT NULL,
ORPHANED BOOLEAN,
PRIMARY KEY(ID)
);