INSERT INTO APPLICATION.LOYALTIES (CODE, DESCRIPTION)
VALUES ('IMP', 'A member of the Imperium.');
INSERT INTO APPLICATION.LOYALTIES (CODE, DESCRIPTION)
VALUES ('IND', 'An independent world, uncommitted to any interstellar group.');
INSERT INTO APPLICATION.LOYALTIES (CODE, DESCRIPTION)
VALUES ('MDC', 'A member of the Darrian Confederation.');
INSERT INTO APPLICATION.LOYALTIES (CODE, DESCRIPTION)
VALUES ('DCC', 'Claimed by the Darrian Confederation.');
INSERT INTO APPLICATION.LOYALTIES (CODE, DESCRIPTION)
VALUES ('MZC', 'A member of the Zhodani Consulate.');
INSERT INTO APPLICATION.LOYALTIES (CODE, DESCRIPTION)
VALUES ('CZC', 'Controlled by the Zhodani Consulate.');
INSERT INTO APPLICATION.LOYALTIES (CODE, DESCRIPTION)
VALUES ('SWC', 'A member of the Sword Worlds Confederation.');
INSERT INTO APPLICATION.SPECIAL_INSTALLATIONS (TYPE, DESCRIPTION)
VALUES ('Capital', 'The world indicated is the seat of government at the subsector (or other interstellar) level. In many cases, this government is independent of the local planetary government. Examples include Subsector Capital, Confederation Capital and Frontier District Capital.');
INSERT INTO APPLICATION.SPECIAL_INSTALLATIONS (TYPE, DESCRIPTION)
VALUES ('Exile Camp', 'A location committed to the containment of individuals guilty (or presumed guilty) of political crimes of discontent. Governmental controls are usually restricted to the retention of inmates and a general oppression of the population.');
INSERT INTO APPLICATION.SPECIAL_INSTALLATIONS (TYPE, DESCRIPTION)
VALUES ('Imperial Prison', 'A penitentiary or rehabilitation center for those guilty of Imperial crimes.');
INSERT INTO APPLICATION.SPECIAL_INSTALLATIONS (TYPE, DESCRIPTION)
VALUES ('Imperial Research Station', 'An installation devoted to one or more research projects of Imperial interest.');
INSERT INTO APPLICATION.SPECIAL_INSTALLATIONS (TYPE, DESCRIPTION)
VALUES ('Imperial Reservation', 'A location, usually very large, under Imperial jurisdiction and restricted to use only by members of the Imperial family or those authorised by a member of the Imperial family.');
INSERT INTO APPLICATION.SPECIAL_INSTALLATIONS (TYPE, DESCRIPTION)
VALUES ('Imperial Way Station', 'A base established for the repair, maintenance and overhaul of Imperial equipment. It may include provisions for Army troop barracks, naval and scout ship overhauls and intelligence operations.');
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Cronor', NULL, 5, 2, NULL, '<p>The Cronor subsector lies at the extreme spinward reach of the Imperial frontier and has long been a point of friction between the Imperium and the Zhodani Consulate. The Second Frontier War (615 - 620) began with an attack on Cipango (0705) and then exploded to engulf three subsectors. Ultimately, the Cronor subsector was lost as a result of the war and the borders established have remained to this day. Zhodani ascendence in this subsector is a relatively recent event, occurring only in the last century. Incursions which have collectively been called the Fourth Frontier War (1082 - 1084) resulted in some realignment of accepted boundaries, but in no real gains for either side.</p><p>Cronor subsector contains a jump route nexus (at Cronor) controlling vital Zhodani connections to territory in both Jewell and Querion subsectors. Away from established jump lanes, the sparse population of the subsector has resisted domination, although only in a passive vein.</p><p>The Cronor subsector contains 24 worlds and a population of 3.682 billion. The highest population level is 9 at Cronor. The highest tech level is D at Cronor. All worlds in this subsector should be treated as Amber by Imperial citizens.</p>');
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Querion', 1, 6, 3, NULL, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Darrian', 2, 7, 4, NULL, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Five Sisters', 3, 8, NULL, NULL, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Jewell', NULL, 9, 6, 1, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Vilis', 5, 10, 7, 2, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Sword Worlds', 6, 11, 8, 3, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'District 268', 7, 12, NULL, 4, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Regina', NULL, 13, 10, 5, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Lanth', 9, 14, 11, 6, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Lunion', 10, 15, 12, 7, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Glisten', 11, 16, NULL, 8, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Aramis', NULL, NULL, 14, 9, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Rhylanor', 13, NULL, 15, 10, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Mora', 14, NULL, 16, 11, NULL);
INSERT INTO APPLICATION.SUB_SECTORS (SECTOR, "NAME", N_NEIGHBOUR, E_NEIGHBOUR, S_NEIGHBOUR, W_NEIGHBOUR, BACKGROUND)
VALUES (1, 'Trin''s Veil', 15, NULL, NULL, 12, NULL);
INSERT INTO APPLICATION.SECTORS ("NAME", BACKGROUND)
VALUES ('The Spinward Marches', '<p>Interstellar directions within the Galaxy are expressed with respect to its shape and rotation. Toward the central core, the term is coreward. Toward the rim and intergalactic space, rimward. In the direction from which the Galaxy is rotating, trailing. In the direction of galactic spin, spinward. These direction conventions provide the name for a frontier of the Imperium called the Spinward Marches.</p><p>At the spinward edge, 120 parsecs from the original center of the Imperium, the Marches represent one of the furthest extents of exploration and domination by Imperial forces. Lying adjacent to territory of the Zhodani Consulate and the Vargr Extents, this region is a site which has seen conflict and intrigue.</p>');
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Zeycude', '0101', 12, 3, 3, 0, 6, 9, 8, 9, NULL, 'Poor|Desert World', NULL, NULL, TRUE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Reno', '0102', 12, 1, 2, 2, 7, 11, 9, 10, 'Z', 'Poor|Non Agricultural', NULL, NULL, TRUE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Errere', '0103', 11, 2, 6, 3, 6, 6, 4, 11, 'Z', 'Rich|Non Industrial', NULL, NULL, FALSE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Cantrel', '0104', 12, 3, 6, 6, 2, 4, 3, 9, NULL, 'Non Industrial', NULL, NULL, FALSE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Gyomar', '0108', 13, 8, 11, 2, 8, 8, 9, 5, NULL, NULL, NULL, NULL, TRUE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Thengo', '0202', 12, 8, 6, 8, 5, 8, 6, 5, NULL, 'Agricultural|Non Industrial', NULL, NULL, TRUE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Rio', '0301', 12, 6, 8, 6, 6, 4, 8, 8, NULL, 'Rich|Agricultural|Non Industrial', NULL, NULL, TRUE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Gesentown', '0303', 11, 2, 1, 1, 6, 9, 11, 12, 'Z', 'Non Agricultural|Non Industrial', NULL, NULL, TRUE, 6, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Cronor', '0304', 10, 6, 3, 6, 9, 3, 4, 13, 'Z', NULL, 'Zhodani Frontier District Capitial', NULL, FALSE, 6, 1, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Atsa', '0307', 11, 4, 3, 3, 7, 12, 10, 10, 'Z', 'Poor|Non Agricultural', NULL, NULL, FALSE, 6, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Whenge', '0503', 13, 6, 4, 8, 5, 0, 0, 8, NULL, 'Agricultural|Non Industrial', NULL, NULL, FALSE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Enlas-du', '0601', 14, 9, 7, 5, 7, 7, 6, 6, NULL, 'Agricultural', NULL, NULL, TRUE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Algebaster', '0605', 12, 6, 6, 5, 6, 5, 8, 9, NULL, 'Rich|Agricultural|Non Industrial', NULL, NULL, FALSE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Rasatt', '0607', 14, 8, 8, 3, 4, 0, 1, 7, NULL, 'Non Industrial', NULL, NULL, FALSE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Ninjar', '0608', 10, 2, 1, 1, 6, 6, 6, 12, 'Z', 'Non Agricultural|Non Industrial', NULL, NULL, FALSE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Sheyou', '0610', 11, 7, 5, 6, 7, 7, 9, 10, 'Z', 'Agricultural', NULL, NULL, TRUE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Indo', '0703', 14, 3, 3, 4, 6, 6, 2, 5, NULL, 'Non Industrial', NULL, NULL, FALSE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Nerewhon', '0704', 14, 7, 3, 8, 4, 7, 5, 7, NULL, 'Non Industrial', NULL, NULL, FALSE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Cipango', '0705', 10, 8, 8, 6, 8, 6, 5, 12, 'Z', 'Rich', NULL, NULL, TRUE, 7, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Stave', '0710', 14, 7, 6, 6, 7, 10, 8, 2, NULL, 'Agricultural', NULL, NULL, TRUE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Narval', '0805', 13, 5, 2, 5, 6, 8, 8, 6, NULL, 'Non Industrial', NULL, 'A', TRUE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Plaven', '0807', 14, 8, 4, 5, 3, 0, 0, 3, NULL, 'Non Industrial', NULL, NULL, FALSE, 2, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Quar', '0808', 11, 5, 3, 2, 7, 2, 0, 11, 'N', 'Poor|Non Agricultural', NULL, 'A', TRUE, 1, NULL, 0);
INSERT INTO APPLICATION.WORLDS (SUB_SECTOR, "NAME", LOCATION, STARPORT, "SIZE", ATMOSPHERE, HYDROGRAPHICS, POPULATION, GOVERNMENT, LAW_LEVEL, TECHNOLOGY, BASES,TRADE, NOTES,TAS_TZC, GAS_GIANT, LOYALTY, SPECIAL_INSTALLATIONS, SEED)
VALUES (1, 'Frond', '0810', 14, 9, 12, 3, 3, 0, 0, 9, NULL, 'Non Industrial', NULL, NULL, TRUE, 2, NULL, 0);